### ISSUE TITLE
请问如何对接开放平台中针对移动app的微信认证

### ISSUE THREAD

**Issue by liudonghua123** [Wechat-Group/weixin-java-open-demo#32]
你好，移动app的微信认证与网页版的还是有一些区别的，请问应该如何接入呢，另外我看
```
wechat:
  open:
    componentAppId: ""
    componentSecret: ""
    componentToken: ""
    componentAesKey: ""
```
看官方文档，一般只需要appid，secret，那token、aeskey是用来做什么用的？
